### PR TITLE
Add automatic version detection to Javadoc badge

### PR DESCRIPTION
**Pull request by valery1707**

### CODE REVIEW

**Comment by dmarkov** [comment]
@valery1707 Thanks, let me find someone who can review this pull request

**Comment by dmarkov** [comment]
@yegor256 review it please, it is a rather short pull request, no need to do a full code review

**Comment by yegor256** [comment]
@rultor merge

**Comment by dmarkov** [comment]
@yegor256 thank you, added **16 mins** to your acc, payment num is `000-2f6173d2`, 98 hours and 19 mins spent in total to complete; review comments (c=1) added as a bonus; +16 to your rating, your total score is [+4498](http://www.netbout.com/b/35008?open=rating)

**Comment by dmarkov** [comment]
@rultor deploy

**Pull request merged**
